from __future__ import annotations


def demo_note_for_market(market: str) -> str | None:
    normalized = market.strip().lower()
    if normalized in {"ai coding tools", "ai coding", "coding agents", "ai developer tools"}:
        return None
    return (
        "CompeteOps v0.6 uses a sample dataset optimized for AI coding tools. "
        "This run preserves your input but demonstrates the AI coding tools workflow."
    )


def competitor_blueprints() -> list[dict]:
    return [
        {
            "name": "Cursor",
            "category": "direct",
            "description": "AI-native code editor focused on codebase chat, completion, and agentic edits.",
            "website_url": "mock://cursor/home",
        },
        {
            "name": "GitHub Copilot",
            "category": "direct",
            "description": "AI coding assistant embedded across the GitHub and IDE developer ecosystem.",
            "website_url": "mock://github-copilot/home",
        },
        {
            "name": "Claude Code",
            "category": "direct",
            "description": "Terminal-oriented agentic coding workflow for editing, debugging, and codebase tasks.",
            "website_url": "mock://claude-code/home",
        },
        {
            "name": "Windsurf",
            "category": "direct",
            "description": "AI coding environment centered on flow-state development and agent-assisted edits.",
            "website_url": "mock://windsurf/home",
        },
        {
            "name": "Replit Agent",
            "category": "direct",
            "description": "Cloud development agent that helps create, run, and deploy software projects.",
            "website_url": "mock://replit-agent/home",
        },
        {
            "name": "Devin",
            "category": "indirect",
            "description": "Autonomous software engineering agent positioned around end-to-end task execution.",
            "website_url": "mock://devin/home",
        },
        {
            "name": "Codex",
            "category": "indirect",
            "description": "Agentic coding assistant for repository understanding, edits, tests, and review workflows.",
            "website_url": "mock://codex/home",
        },
    ]


def evidence_blueprints() -> list[dict]:
    return [
        {
            "key": "cursor_product",
            "competitor": "Cursor",
            "source_title": "Mock Cursor Product Brief",
            "source_type": "mock",
            "source_url": "mock://cursor/product",
            "dimension": "product",
            "claim": "Cursor competes through an AI-native IDE experience with codebase-aware assistance.",
            "evidence_text": "Mock product notes describe code completion, chat with codebase, and agentic editing as the core workflow.",
            "confidence": "medium",
        },
        {
            "key": "cursor_pricing",
            "competitor": "Cursor",
            "source_title": "Mock Cursor Pricing Snapshot",
            "source_type": "mock",
            "source_url": "mock://cursor/pricing",
            "dimension": "pricing",
            "claim": "Cursor is modeled as a prosumer-to-team subscription product with free, pro, and team motions.",
            "evidence_text": "Mock pricing notes include a free entry point, individual paid plan, team plan, and enterprise conversation path.",
            "confidence": "medium",
        },
        {
            "key": "cursor_user_voice",
            "competitor": "Cursor",
            "source_title": "Mock Cursor User Voice",
            "source_type": "mock",
            "source_url": "mock://cursor/user-voice",
            "dimension": "user_voice",
            "claim": "Users value integrated workflow but raise concerns about pricing, reliability, and usage transparency.",
            "evidence_text": "Mock review snippets praise in-editor context and complain about opaque limits, occasional flaky generations, and cost predictability.",
            "confidence": "medium",
        },
        {
            "key": "copilot_product",
            "competitor": "GitHub Copilot",
            "source_title": "Mock GitHub Copilot Product Brief",
            "source_type": "mock",
            "source_url": "mock://github-copilot/product",
            "dimension": "product",
            "claim": "GitHub Copilot benefits from broad IDE distribution and deep adjacency to GitHub workflows.",
            "evidence_text": "Mock product notes highlight code completion, chat, pull request assistance, and repository workflow integration.",
            "confidence": "medium",
        },
        {
            "key": "copilot_pricing",
            "competitor": "GitHub Copilot",
            "source_title": "Mock GitHub Copilot Pricing Snapshot",
            "source_type": "mock",
            "source_url": "mock://github-copilot/pricing",
            "dimension": "pricing",
            "claim": "GitHub Copilot is modeled as an ecosystem-bundled subscription with individual, business, and enterprise paths.",
            "evidence_text": "Mock pricing notes emphasize paid individual seats, organization plans, and enterprise governance packaging.",
            "confidence": "medium",
        },
        {
            "key": "copilot_positioning",
            "competitor": "GitHub Copilot",
            "source_title": "Mock Copilot Positioning Note",
            "source_type": "mock",
            "source_url": "mock://github-copilot/positioning",
            "dimension": "positioning",
            "claim": "Copilot's strategic advantage is distribution through existing developer tools rather than a standalone editor wedge.",
            "evidence_text": "Mock positioning notes describe ecosystem bundling as a pressure point for standalone AI coding products.",
            "confidence": "medium",
        },
        {
            "key": "claude_product",
            "competitor": "Claude Code",
            "source_title": "Mock Claude Code Product Brief",
            "source_type": "mock",
            "source_url": "mock://claude-code/product",
            "dimension": "product",
            "claim": "Claude Code is positioned around terminal-native agentic coding and codebase task execution.",
            "evidence_text": "Mock product notes describe terminal workflows, repository edits, debugging, and multi-file task execution.",
            "confidence": "medium",
        },
        {
            "key": "claude_pricing",
            "competitor": "Claude Code",
            "source_title": "Mock Claude Code Commercial Snapshot",
            "source_type": "mock",
            "source_url": "mock://claude-code/pricing",
            "dimension": "pricing",
            "claim": "Claude Code is modeled as usage-sensitive and tied to broader AI assistant subscription or API economics.",
            "evidence_text": "Mock commercial notes flag usage limits and model-cost exposure as relevant buyer concerns.",
            "confidence": "medium",
        },
        {
            "key": "windsurf_product",
            "competitor": "Windsurf",
            "source_title": "Mock Windsurf Product Brief",
            "source_type": "mock",
            "source_url": "mock://windsurf/product",
            "dimension": "product",
            "claim": "Windsurf competes as an AI coding environment that emphasizes developer flow and agent collaboration.",
            "evidence_text": "Mock product notes include codebase context, flow-aware editing, and agent-assisted changes.",
            "confidence": "medium",
        },
        {
            "key": "windsurf_user_voice",
            "competitor": "Windsurf",
            "source_title": "Mock Windsurf User Voice",
            "source_type": "mock",
            "source_url": "mock://windsurf/user-voice",
            "dimension": "user_voice",
            "claim": "Users respond to fast iteration but still compare quality and reliability against better-known AI coding tools.",
            "evidence_text": "Mock review snippets highlight speed and novelty while asking for stronger enterprise controls and predictable behavior.",
            "confidence": "medium",
        },
        {
            "key": "replit_product",
            "competitor": "Replit Agent",
            "source_title": "Mock Replit Agent Product Brief",
            "source_type": "mock",
            "source_url": "mock://replit-agent/product",
            "dimension": "product",
            "claim": "Replit Agent differentiates through browser-based creation, hosting, and deployment rather than local IDE replacement.",
            "evidence_text": "Mock product notes connect prompt-to-app creation with cloud runtime and deployment workflows.",
            "confidence": "medium",
        },
        {
            "key": "replit_pricing",
            "competitor": "Replit Agent",
            "source_title": "Mock Replit Agent Pricing Snapshot",
            "source_type": "mock",
            "source_url": "mock://replit-agent/pricing",
            "dimension": "pricing",
            "claim": "Replit Agent is modeled as a hybrid seat-and-usage product connected to hosted development.",
            "evidence_text": "Mock pricing notes include free experimentation, paid account upgrades, and usage-linked agent capacity.",
            "confidence": "medium",
        },
        {
            "key": "devin_positioning",
            "competitor": "Devin",
            "source_title": "Mock Devin Positioning Note",
            "source_type": "mock",
            "source_url": "mock://devin/positioning",
            "dimension": "positioning",
            "claim": "Devin is an indirect competitor because it frames the job-to-be-done as autonomous engineering execution.",
            "evidence_text": "Mock positioning notes describe end-to-end engineering tasks rather than IDE-level augmentation.",
            "confidence": "medium",
        },
        {
            "key": "codex_positioning",
            "competitor": "Codex",
            "source_title": "Mock Codex Positioning Note",
            "source_type": "mock",
            "source_url": "mock://codex/positioning",
            "dimension": "positioning",
            "claim": "Codex is an indirect competitor around repository-level agentic development and review workflows.",
            "evidence_text": "Mock positioning notes describe repo edits, tests, bug fixing, and code review assistance as core workflows.",
            "confidence": "medium",
        },
        {
            "key": "market_incumbents",
            "competitor": None,
            "source_title": "Mock Market Signal: Incumbent Bundling",
            "source_type": "mock",
            "source_url": "mock://market/incumbent-bundling",
            "dimension": "market_signal",
            "claim": "Large incumbents can pressure standalone AI coding products by bundling assistants into existing ecosystems.",
            "evidence_text": "Mock market notes identify IDE, repository, and cloud-platform distribution as the strongest incumbent advantage.",
            "confidence": "medium",
        },
        {
            "key": "risk_model_cost",
            "competitor": None,
            "source_title": "Mock Risk Note: Model Cost Pressure",
            "source_type": "mock",
            "source_url": "mock://risk/model-cost-pressure",
            "dimension": "risk",
            "claim": "Model cost and latency can compress margins unless products use routing, caching, and tiering.",
            "evidence_text": "Mock risk notes flag heavy agentic workflows as more expensive than lightweight autocomplete.",
            "confidence": "medium",
        },
    ]
